#!/bin/sh

# script/test: Run test suite for application. Optionally pass in a path to an
#              individual test file to run a single test.


set -e

cd "$(dirname "$0")/../.."

script/docker/update

echo "==> Running tests…"

if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  bin/rake test "$1"
else
  bin/rake test
fi
