#!/bin/sh

# script/cubuild: Resolve all dependencies that the application requires to
#                   run.

set -eu

cd "$(dirname "$0")/.."

echo "==> Updating gems…"
bundle install --deployment --path vendor/bundle

echo "==> Setup database…"
bundle exec rake db:setup
bundle exec rake db:test:prepare

echo "==> Running tests…"
bundle exec rake spec
