#!/bin/bash

# script/cleanup: Delete any unnecessary or temporary files.

set -eu

cd "$(dirname "$0")/.."

docker-compose run --rm web script/docker/cleanup

docker-compose stop &> /dev/null || true &> /dev/null
docker-compose rm --force &> /dev/null || true &> /dev/null
docker ps -a -q -f status=exited | while IFS='' read -r cont_id
do
  docker stop "$cont_id" &> /dev/null || true &> /dev/null
  docker rm -v "$cont_id" &> /dev/null || true &> /dev/null
done

docker images --filter 'dangling=true' -q --no-trunc | while IFS='' read -r image_id
do
  docker rmi "${image_id}" &> /dev/null || true &> /dev/null
done