#!/bin/bash

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Updating db…"
# run update script inside a container
docker-compose run --rm web script/docker/update
